[theme]
primaryColor = "#007c89"
backgroundColor = "#f6f8fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#17202a"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
